# Generated by Django 3.2.6 on 2021-08-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MMMM',
        ),
    ]
