# Generated by Django 3.2.6 on 2021-08-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_newcontractmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewContractModel',
        ),
    ]
