# Generated by Django 3.2.6 on 2021-08-21 20:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_newcontractmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontractmodel',
            name='addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='newcontractmodel',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None),
        ),
    ]
